name: Checkbox Workflow
'on':
  workflow_dispatch:
    inputs:
      environments:
        description: Select environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - prod
      checkbox_1:
        description: Kops Installation
        required: true
        default: 'false'
      checkbox_2:
        description: EFK Installation
        required: false
        default: 'false'
      checkbox_3:
        description: Monitoring Installation
        required: false
        default: 'false'
jobs:
  run_workflow:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Run workflow based on checkboxes and run commands
        run: | 
          if [ "${{ github.event.inputs.checkbox_1 }}" == "true" ]; then
            echo "installation for Kops"
            # Your command for Checkbox 1 goes here
      - name: Set AWS credentials
        run: |
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws configure set default.region us-west-2
          
      - name: Install kops and AWS CLI
        run: |
          wget
          https://github.com/kubernetes/kops/releases/download/v1.28.1/kops-linux-amd64
          sudo mv kops-linux-amd64 /usr/local/bin/kops
          sudo chmod +x /usr/local/bin/kops 
          which kops 
          kops version
          sudo apt-get update && sudo apt-get install -y awscli
          aws s3api create-bucket --bucket kops-bucket-new-testing --region
          us-west-2
          aws s3 ls 
          aws s3 ls kops-bucket-new-testing
          aws s3api put-bucket-versioning --bucket kops-bucket-new-testing
          --region us-west-2 --versioning Status=Enabled

          export KOPS_STATE_STORE=s3://kops-bucket-new-testing


          fi

          if [ "${{ github.event.inputs.checkbox_2 }}" == "true" ]; then
            echo "installation for EFK"
            # Your command for Checkbox 3 goes here
          fi

          if [ "${{ github.event.inputs.checkbox_3 }}" == "true" ]; then
            echo "installation for monitoring"
            # Your command for Checkbox 4 goes here
          fi 
