name: Checkbox Workflow
'on':
  workflow_dispatch:
    inputs:
      environments:
        description: Select environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - prod
      checkbox_1:
        description: 'Kops Installation'
        required: false
        default: 'false'
      checkbox_2:
        description: 'EFK Installation'
        required: false
        default: 'false'
      checkbox_3:
        description: 'Monitoring Installation'
        required: false
        default: 'false'
jobs:
  run_workflow:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
         if [ "${{ github.event.inputs.checkbox_1 }}" == "true" ]; then
           echo "installation for Kops"
           # Your command for Checkbox 2 goes here
         fi

         if [ "${{ github.event.inputs.checkbox_2 }}" == "true" ]; then
           echo "installation for EFK"
           # Your command for Checkbox 3 goes here
         fi

         if [ "${{ github.event.inputs.checkbox_3 }}" == "true" ]; then
           echo "installation for monitoring"
           # Your command for Checkbox 4 goes here
         fi
